title: Matheus Mariano
description: Engenheiro de Software | Especialista em IA, Prompt Engineering e Govtech
url: "https://matheusmarnt.github.io"
baseurl: ""

author: Matheus Mariano
email: matheus.marnt@gmail.com
linkedin: SEU_USUARIO_DO_LINKEDIN
github: matheusmarnt
location: Gurupi, Tocantins, Brasil

nav:
  - name: Início
    link: /#inicio
  - name: Sobre
    link: /#sobre
  - name: Projetos
    link: /#projetos
  - name: Contato
    link: /#contato

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap